[package]
name = "ruspiro-timer"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.3.0" # remember to update html_root_url
description = "This crates provides simple timing functions to pause the current core for a specific amount of time."
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-timer"
documentation = "https://docs.rs/ruspiro-timer/0.3.0"
readme = "README.md"
keywords = ["RusPiRo", "baremetal", "raspberrypi", "timer"]
categories = ["no-std", "embedded"]
edition = "2018"

[lib]

[dependencies]
ruspiro-register = { path = "../register", version = "0.3" }

[features]
default = ["ruspiro_pi3"]
ruspiro_pi3 = []